$ nano k8s-deployment.yaml
apiVersion: apps/v1
kind: deployment
metadata:
    name: php-webapp
spec:
    replicas: 1
    selector:
        matchLables:
            app: php-webapp
    template:
        metadata:
            labels:
                app: php-webapp
        spec: 
            containers:
            - name: php-webapp
              image: ghcr.io/fwwznabila/myphp-app/myphp-app:latest
              ports:
              - containerPort: 80
              
 ---
 apiVersion: v1
 kind: Service
 metadata:
    name: php-webapp-service
 spec:
    type: LoadBalancer
    selector:
        app: php-webapp
    ports:
    - port: 80
      targetPort: 80